;Remove previous files
RMDir /r "$INSTDIR\data"
RMDir /r "$INSTDIR\generic"
RMDir /r "$INSTDIR\iconengines"
RMDir /r "$INSTDIR\imageformats"
RMDir /r "$INSTDIR\multimedia"
RMDir /r "$INSTDIR\networkinformation"
RMDir /r "$INSTDIR\platforms"
RMDir /r "$INSTDIR\sqldrivers"
RMDir /r "$INSTDIR\styles"
RMDir /r "$INSTDIR\tls"
Delete "$INSTDIR\*.dll"
Delete "$INSTDIR\COPYING"
Delete "$INSTDIR\ReadMe.txt"
Delete "$INSTDIR\FritzCallIndicator.exe"
Delete "$INSTDIR\Uninstall.exe"
