name: "Windows"

# manual trigger
on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  Windows_Qt6:
    name: Win 2022 Qt 6
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.2'
        cache: 'true'
        cache-key-prefix: install-qt-action
        dir: 'C:\'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        modules: 'qtmultimedia'
        tools: 'tools_mingw1310'

    - name: Set env
      shell: pwsh
      run: |
       echo "C:/Qt/Tools/mingw1310_64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
       $env:PATH = "C:\Qt\Tools\mingw1310_64\bin;$env:PATH"

    - name: Compile
      run: |
       mkdir build
       cd build
       cmake -DCMAKE_PREFIX_PATH="${{env.Qt6_Dir}}" -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" ..
       mingw32-make

    - name: Create Package
      shell: cmd
      run: |
       mkdir FritzCallIndicator\data
       copy build\src\FritzCallIndicator.exe FritzCallIndicator\FritzCallIndicator.exe
       windeployqt --release --no-translations --no-opengl-sw FritzCallIndicator\FritzCallIndicator.exe
       copy COPYING FritzCallIndicator\
       copy packaging\windows\ReadMe.txt FritzCallIndicator\
       copy data\country_codes.csv FritzCallIndicator\data\
       xcopy /i /e /s data\area_codes FritzCallIndicator\data\area_codes\
       xcopy /i /e /s data\online_resolvers FritzCallIndicator\data\online_resolvers\
       git rev-parse --short main > buildnr.txt
       set /p buildnr= < buildnr.txt
       del buildnr.txt
       set output_zip=FritzCallIndicator-Windows_%buildnr%.zip
       7z a %output_zip% .\FritzCallIndicator\
       copy packaging\windows\fritzcallindicator.nsi .
       copy packaging\windows\removeprevious.nsh .
       copy icons\fritzcallindicator.ico .
       makensis fritzcallindicator.nsi
       ren FritzCallIndicator_Installer.exe FritzCallIndicator-Windows_%buildnr%.exe

    - uses: actions/upload-artifact@v4
      with:
        name: FritzCallIndicator-Windows_Artefacts
        path: FritzCallIndicator-Windows_*.*
        retention-days: 3
        overwrite: true
